/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/Base/AppFooter.vue')['default']
    AppFooterItem: typeof import('./../components/Base/AppFooterItem.vue')['default']
    AppIntro: typeof import('./../components/Base/AppIntro.vue')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    DemoHeading: typeof import('./../components/Base/DemoHeading.vue')['default']
    IonArrowBack: typeof import('~icons/ion/arrow-back')['default']
    NewDiscussionForm: typeof import('./../components/Base/NewDiscussionForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagsInput: typeof import('./../components/TagsInput/TagsInput.vue')['default']
    TagsInputV2: typeof import('./../components/TagsInput/TagsInputV2.vue')['default']
    TagsInputV3: typeof import('./../components/TagsInput/TagsInputV3.vue')['default']
    TwemojiFlagBrazil: typeof import('~icons/twemoji/flag-brazil')['default']
    TwemojiLeftArrowCurvingRight: typeof import('~icons/twemoji/left-arrow-curving-right')['default']
  }
}
