/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/Base/AppFooter.vue')['default']
    AppFooterItem: typeof import('./../components/Base/AppFooterItem.vue')['default']
    AppIntro: typeof import('./../components/Base/AppIntro.vue')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    DemoHeading: typeof import('./../components/Base/DemoHeading.vue')['default']
    IonArrowBack: typeof import('~icons/ion/arrow-back')['default']
    NewDiscussionForm: typeof import('./../components/Base/NewDiscussionForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagsInputInline: typeof import('./../components/TagsInput/TagsInputInline.vue')['default']
    TagsInputStacked: typeof import('./../components/TagsInput/TagsInputStacked.vue')['default']
    TagsInputV1: typeof import('./../components/TagsInput/TagsInputV1.vue')['default']
    TagsInputV2: typeof import('./../components/TagsInput/TagsInputV2.vue')['default']
    TagsInputV3: typeof import('./../components/TagsInput/TagsInputV3.vue')['default']
    TagsInputV4: typeof import('./../components/TagsInput/TagsInputV4.vue')['default']
    TwemojiFlagBrazil: typeof import('~icons/twemoji/flag-brazil')['default']
    TwemojiLeftArrowCurvingRight: typeof import('~icons/twemoji/left-arrow-curving-right')['default']
  }
}
